spreadsheetCreated(spreadsheetUrl) ::= <<
<div style="font-family:Arial, Helvetica, sans-serif;width:580px;margin:0 10px 15px 10px;color:#3C6995;font-size:13px">
	<p>Finally you can start managing your ebay inventory through the Google Docs spreadsheet:</p>
	<p>
		<a href="$spreadsheetUrl$">$spreadsheetUrl$</a>
	</p>
	<p> 
To make it work, please modify only cells with inventory i.e. 
<ul>
			<li>do not change any other cells like variation titles, listing numbers or titles,</li>
			<li>do not move/copy/delete cells and rows.</li>
		</ul>
We are working on full inventory management feature set that will also include adding and deleting new listings. 
If you need any specific feature, please do let us know and we will roll out such a new feature within 2 weeks. 
	</p>
	<p>
Thank you,<br />
Maciej Zywno,<br /> 
the founder
	</p>
</div>
>>