welcome() ::= <<
<div style="font-family:Arial, Helvetica, sans-serif;width:580px;margin:0 10px 15px 10px;color:#3C6995;font-size:13px">
	<p>Thank you for your interest in our ebay inventory management software.</p>

	<p>We are already fetching your active listings and putting the data into a Google Docs spreadsheet. 
This should not take longer than a few minutes depending on how many items you sell.
Once we're done we will send you another message so that you can actually start using the software. 
	</p>
	<p>
Thank you,<br/>
Maciej Zywno,<br/> 
the founder
	</p>
	<p style="font-size: 10px; ">footer text.</p>
</div>
>>